language: r

sudo: false

cache: packages

r_packages:
  - covr
  - testthat

bioc_packages:
  - limma
  - gespeR
  - pmm
  - AnnotationDbi
  - GOstats
  - org.Hs.eg.db
  - RankAggreg
  
r_github_packages: dirmeier/diffusr 

cache: packages

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"

after_success:
  - Rscript -e 'library(covr); codecov()'
