language: r
r: bioc-release

sudo: false

cache: packages

os:
  - osx
  - linux

r_packages:
  - covr
  - testthat
  - lintr

bioc_packages:
  - limma
  - gespeR
  - AnnotationDbi
  - GOstats
  - org.Hs.eg.db
  - RankAggreg
  - BiocCheck

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"

after_success:
  - Rscript -e 'library(covr); codecov()'
  - Rscript -e 'lintr::lint_package()'
  - R CMD BiocCheck $PKG_TARBALL
