language: r
r: bioc-devel

sudo: false

cache: packages

os:
  - osx
  - linux

r_packages:
  - covr
  - testthat
  - lintr

bioc_packages:
  - limma
  - BiocCheck
  - BiocStyle

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
    - LINTR_COMMENT_BOT=false

after_success:
  - Rscript -e 'library(covr); codecov()'
  - Rscript -e 'lintr::lint_package()'
  - R CMD BiocCheck $PKG_TARBALL
