language: r

sudo: false

cache: packages

r_packages:
  - covr
  - testthat

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"

after_success:
  - Rscript -e 'library(covr); codecov()'
